apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-app
  template:
    metadata:
      labels:
        app: delivery-app
    spec:
      initContainers:
        - name: wait-pg
          image: waisbrot/wait
          env:
            - name: TARGETS
              value: postgres:5432
      containers:
      - name: delivery
        image: dkuser2/otus-saga-28:v1
        workingDir: /app/delivery
        command: ["python"]
        args: ["manage.py", "runserver", "0:8000"]
        env:
          - name: DJANGO_ENV
            value: DEV
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DJANGO_SECRET_KEY
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_PORT
          - name: STORE_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: STORE_SERVICE
          - name: TRANSACTION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: TRANSACTION_SERVICE
          - name: DELIVERY_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DELIVERY_SERVICE
        ports:
        - name: web
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery-app
spec:
  selector:
    app: delivery-app
  ports:
    - protocol: TCP
      port: 8000
      name: web
      targetPort: web
  type: NodePort
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delivery-migrate-job-4
  labels:
    app: migrate-job
spec:
  template:
    metadata:
      name: migrate-job
      labels:
        app: migrate-job
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-pg
        image: waisbrot/wait
        env:
          - name: TARGETS
            value: postgres:5432
      containers:
      - name: insert
        env:
          - name: DJANGO_ENV
            value: DEV
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DJANGO_SECRET_KEY
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_PORT
          - name: STORE_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: STORE_SERVICE
          - name: TRANSACTION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: TRANSACTION_SERVICE
          - name: DELIVERY_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DELIVERY_SERVICE
        image: dkuser2/otus-saga-28:v1
        workingDir: /app/delivery
        command: ["python", "manage.py", "migrate"]
  backoffLimit: 0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delivery-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /delivery(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: delivery
            port:
              number: 8000