apiVersion: apps/v1
kind: Deployment
metadata:
  name: finderconsumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finderconsumer-app
  template:
    metadata:
      labels:
        app: finderconsumer-app
    spec:
      containers:
      - name: finderconsumer
        image: dkuser2/otus-project:v1
        workingDir: /app
        command: ["make"]
        args: ["finder_consumer"]
        env:
          - name: DATABASE_NAME
            value: finder
          - name: DJANGO_ENV
            value: dev
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DJANGO_SECRET_KEY
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_PORT
          - name: STORE_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: STORE_SERVICE
          - name: TRANSACTION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: TRANSACTION_SERVICE
          - name: DELIVERY_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DELIVERY_SERVICE
          - name: FINDER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: FINDER_SERVICE
          - name: NOTIFICATION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: NOTIFICATION_SERVICE
          - name: KAFKA_SERVER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: KAFKA_SERVER
          - name: REDIS_SERVER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: REDIS_SERVER
          - name: ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: ROOT_PASSWORD
          - name: ROOT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: ROOT_TOKEN
        ports:
        - name: web
          containerPort: 8000

