apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pomsaga
spec:
  jobLabel: pomsaga
  selector:
    matchLabels:
      app: saga-app
  endpoints:
  - interval: 15s
    port: web
    path: /metrics
