apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-app
  template:
    metadata:
      labels:
        app: transaction-app
    spec:
      containers:
      - name: transaction
        image: dkuser2/otus-project:v1
        workingDir: /app
        command: ["make"]
        args: ["transaction"]
        env:
          - name: DATABASE_NAME
            value: transaction
          - name: DJANGO_ENV
            value: dev
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DJANGO_SECRET_KEY
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_PORT
          - name: STORE_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: STORE_SERVICE
          - name: TRANSACTION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: TRANSACTION_SERVICE
          - name: DELIVERY_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DELIVERY_SERVICE
          - name: FINDER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: FINDER_SERVICE
          - name: NOTIFICATION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: NOTIFICATION_SERVICE
          - name: KAFKA_SERVER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: KAFKA_SERVER
          - name: REDIS_SERVER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: REDIS_SERVER
          - name: ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: ROOT_PASSWORD
          - name: ROOT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: ROOT_TOKEN
        ports:
        - name: web
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: transaction
  labels:
    app: transaction-app
spec:
  selector:
    app: transaction-app
  ports:
    - protocol: TCP
      port: 8000
      name: web
      targetPort: web
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /transaction(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: transaction
            port:
              number: 8000