# Generated by Django 3.2.9 on 2022-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=200)),
                ("cost", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
