# Generated by Django 3.2.9 on 2022-02-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactionapp", "0002_alter_balance_sum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order_id",
            field=models.IntegerField(unique=True),
        ),
    ]
