version: "3.7"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword
  STORE_SERVICE: "http://store:8000"
  TRANSACTION_SERVICE: "http://transaction:8000"
  DELIVERY_SERVICE: "http://delivery:8000"
  KAFKA: kafka:9092

services:
  saga:
    image: dkuser2/otus-saga-28:v1
    build: .
    command: make saga
    volumes:
      - .:/app
    environment: *app-config
    depends_on:
      - db
      - store
      - transaction
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  store:
    build: .
    command: make store
    volumes:
      - .:/app
    environment:
      <<: *app-config
    depends_on:
      - db
      - kafka
    ports:
      - "8001:8000"
    stdin_open: true
    tty: true

  finder:
    build: .
    command: make finder
    volumes:
      - .:/app
    environment:
      <<: *app-config
    depends_on:
      - db
      - kafka
    ports:
      - "8004:8000"
    stdin_open: true
    tty: true

  transaction:
    build: .
    command: make transaction
    volumes:
      - .:/app
    environment: *app-config
    depends_on:
      - db
    ports:
      - "8002:8000"
    stdin_open: true
    tty: true

  delivery:
    build: .
    command: make delivery
    volumes:
      - .:/app
    environment: *app-config
    depends_on:
      - db
    ports:
      - "8003:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:12.5-alpine
    environment: *app-config
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "9090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181