saga:
	cd saga && python manage.py runserver 0:8000

store:
	cd store && python manage.py runserver 0:8000

transaction:
	cd transaction && python manage.py runserver 0:8000

delivery:
	cd delivery && python manage.py runserver 0:8000

.PHONY: saga store transaction delivery
