apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-py-app
  template:
    metadata:
      labels:
        app: hello-py-app
    spec:
      containers:
      - name: hello-py
        image: dkuser2/otus-bff-lesson12:v1
        env:
          - name: DJANGO_ENV
            value: DEV
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DJANGO_SECRET_KEY
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: DATABASE_PORT
          - name: GREETING
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: GREETING
        ports:
        - name: web
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: 8000
            path: /
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
