# Generated by Django 3.2.9 on 2022-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
