# Generated by Django 3.2.9 on 2022-03-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=200)),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
