# Generated by Django 3.2.9 on 2022-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifyapp", "0003_alter_log_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="item",
            field=models.TextField(blank=True),
        ),
    ]
