# Generated by Django 3.2.9 on 2022-02-13 05:35

from django.contrib.auth.models import User
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sagaapp", "0001_initial"),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        User.objects.create_superuser("admin", "admin@admin.ru", password="admin")

    operations = [
        migrations.RunPython(forwards_func),
    ]
