{
 "title": "MYAPP DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Errors, %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{}[2m]))",
     "legendFormat": "%"
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total{}[2m]))"
    }
   ]
  },
  {
   "title": "Latency, ms,",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket{}[1m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket{}[1m]))) * 10000"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket{}[1m]))) * 10000"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket{}[1m]))) * 10000"
    },
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total{http_status=~\"5.*\"}[2m]))"
    }
   ]
  }
 ]
}