# Generated by Django 3.2.9 on 2022-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactionapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="sum",
            field=models.IntegerField(default=0),
        ),
    ]
