# Generated by Django 3.2.9 on 2022-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveryapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="committed",
        ),
    ]
